[package]
name = "sandia-decay-example"
edition.workspace = true
publish = false

[[bin]]
path = "main.rs"
name = "sandia-decay-example"

[dependencies]
sdecay.workspace = true
anyhow.workspace = true
clap.workspace = true

[lints]
workspace = true
