[package]
name = "example-batch-decay"
edition.workspace = true
publish = false

[[bin]]
path = "main.rs"
name = "example-batch-decay"

[dependencies]
sdecay.workspace = true
anyhow.workspace = true
clap.workspace = true

[lints]
workspace = true
