[package]
name = "sdecay"
version = "0.1.0"
edition = "2024"

[dependencies]
sdecay-sys = { path = "../sys" }
# these are proc macros
nolt = { path = "nolt" }

[features]
# default = []
default = ["std"]
std = ["alloc"]
alloc = []

[lints]
workspace = true
