[package]
name = "doc-example"
edition.workspace = true
publish = false

[[bin]]
path = "main.rs"
name = "doc-example"

[dependencies]
sdecay = { workspace = true, features = [ "database-min" ] }

[lints]
workspace = true

