# source: https://gist.github.com/antonengelhardt/f44815b91946440a2ac2c60976638686
name: Docs
on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly

      # cred: https://github.com/actions/cache/blob/main/examples.md#rust---cargo
      - name: Cargo registry cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

      # - name: Install typos
      #   run: cargo install typos-cli

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install cargo-docsrs
        run: cargo install cargo-docs-rs

      - name: Generate documentation
        env:
          RUSTDOCFLAGS: -Dwarnings
        run: |
          cargo +nightly docs-rs \
          -p sdecay \
          --target x86_64-unknown-linux-gnu

      - name: Fix file permissions
        shell: sh
        run: |
            chmod -c -R +rX "./target/x86_64-unknown-linux-gnu/doc" |
            while read line; do
                echo "::warning title=Invalid file permissions automatically fixed::$line"
            done

      - name: Generate index.html file
        run: |
            echo "<meta http-equiv=refresh content=0;url=wasm_oidc_plugin/index.html>" > ./target/x86_64-unknown-linux-gnu/doc/index.html

      - name: Upload documentation
        if: ${{ !env.ACT }}
        uses: actions/upload-pages-artifact@v3
        with:
            path: ./target/x86_64-unknown-linux-gnu/doc


  deploy-github-pages:
    if: ${{ !github.event.act }} # skip during local actions testing
    needs: build-docs
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.pages.outputs.page_url }}

    steps:
      - name: Deploy documentation
        id: pages
        uses: actions/deploy-pages@v4
